name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nandinichatterjee/my-dayoff-app:latest

      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}

      - name: Deploy updated container
        run: |
          docker stop my-dayoff-app || true
          docker rm my-dayoff-app || true
          docker run -d -p 8080:8080 \
            --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --env S3_BUCKET=${{ secrets.S3_BUCKET }} \
            --env AWS_REGION=${{ secrets.AWS_REGION }} \
            --env MONGO_URI=${{ secrets.MONGO_URI }} \
            --env MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }} \
            --env MONGO_COLLECTION_NAME=${{ secrets.MONGO_COLLECTION_NAME }} \
            --env SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} \
            --name my-dayoff-app nandinichatterjee/my-dayoff-app:latest

